export const NOTIFY_TIME_LEFT_SECONDS = 5 * 60; // Notify when 5 minutes are left in a session

export const APP_ACTION = {
  ADD_BLOCKED_SITE: 'ADD_BLOCKED_SITE',
  REMOVE_BLOCKED_SITE: 'REMOVE_BLOCKED_SITE',
  START_FOCUS: 'START_FOCUS',
  START_WORK_SESSION: 'START_WORK_SESSION',
  END_WORK_SESSION_EARLY: 'END_WORK_SESSION_EARLY',
  SCHEDULER_EVALUATE: 'SCHEDULER_EVALUATE',
  SET_WORK_START_REMINDER: 'SET_WORK_START_REMINDER',
  CLEAR_WORK_START_REMINDER: 'CLEAR_WORK_START_REMINDER',
  SET_COIN_BALANCE: 'SET_COIN_BALANCE',
  INITIALIZE_FROM_ONBOARDING: 'INITIALIZE_FROM_ONBOARDING',
  RECESS_PICKER_SELECT_RECESS: 'RECESS_PICKER_SELECT_RECESS',
  RECESS_PICKER_REROLL: 'RECESS_PICKER_REROLL',
  RECESS_PICKER_SET_SHOWN_COMBINATIONS: 'RECESS_PICKER_SET_SHOWN_COMBINATIONS',
  QUIZ_SELECT_OPTION: 'QUIZ_SELECT_OPTION',
  QUIZ_RESTART: 'QUIZ_RESTART',
} as const;

export const SCHEDULER_PHASE = {
  FOCUS_BLOCK: 'FOCUS_BLOCK',
  REWARD_GAME: 'REWARD_GAME',
  RECESS: 'RECESS',
} as const;

export const WORK_SESSION_DURATION = 2 * 60 * 60;

export const DEFAULT_BLOCK_LIST_ENTRIES = [
  'youtube.com',
  'instagram.com',
  'facebook.com',
  'messenger.com',
  'web.whatsapp.com',
  'discord.com',
  'tiktok.com',
  'netflix.com',
  'primevideo.com',
  'amazon.com',
  'reddit.com',
] as const;

export const DEFAULT_REROLLS = 3;
export const REWARD_OPTIONS_COUNT = 3;

export const MAX_FOCUS_SESSION_DURATION = 60 * 60;
export const MIN_FOCUS_SESSION_DURATION = 15 * 60;

export const MAX_BREAK_DURATION = 20 * 60;
export const MIN_BREAK_DURATION = 5 * 60;
export const DEFAULT_BREAK_DURATION_SECONDS = 10 * 60; // 10 minutes

export const SEGMENT_COUNT = 8;
export const MAX_SPEED = 0.5;
export const DECEL_FACTOR = 0.99;
export const ACCEL_FACTOR = 0.07;
export const TICKER_MAX_TILT = 20;

export const SPIN_ROTATIONS = 4;
export const SLOTS_DECISION_WINDOW_SECONDS = 5;
export const SLOTS_ANIMATION_DURATION_SECONDS = 3;
export const SLOTS_REEL_STOP_INTERVAL_SECONDS = 1;
